---

- name: Verify
  hosts: o
  tasks:
    - name: Get ansible version
      ansible.builtin.command: ansible --version  # noqa command-instead-of-module
      changed_when: false
      register: v1
    - name: Validate ansible
      ansible.builtin.assert:
        that: v1.rc == 0
